# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json .
RUN npm ci --ignore-scripts
COPY index.ts .
RUN npm run build

# Runtime stage
FROM node:lts-alpine
WORKDIR /app

# Copy runtime dependencies
COPY package.json package-lock.json .
RUN npm ci --production --ignore-scripts

# Copy built files
COPY --from=builder /app/dist ./dist

# Ensure executable permissions
RUN chmod +x dist/index.cjs

EXPOSE 3000
ENTRYPOINT ["node", "dist/index.cjs"]
