[package]
name = "searchdb_native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["napi4"] }
napi-derive = "2"
ahash = "0.8"

[build-dependencies]
napi-build = "2"

[profile.release]
codegen-units = 1
opt-level = 3
lto = true

